from __future__ import annotations


class NodeType:
    DOMAIN = "domain"
    SUBDOMAIN = "subdomain"
    IP_ADDRESS = "ip_address"
    HOST = "host"
    TECHNOLOGY = "technology"
    FRAMEWORK = "framework"
    LIBRARY = "library"
    ENDPOINT = "endpoint"
    API_ROUTE = "api_route"
    PARAMETER = "parameter"
    AUTH_METHOD = "authentication_method"
    SESSION = "session"
    CLOUD_RESOURCE = "cloud_resource"
    BUCKET = "bucket"
    FUNCTION = "function"
    FINDING = "finding"
    VULNERABILITY = "vulnerability"
    MISCONFIGURATION = "misconfiguration"
    EVIDENCE = "evidence"
    REQUEST = "request"
    RESPONSE = "response"
    CODE_SNIPPET = "code_snippet"
    SECRET = "secret"
    PORT = "port"
    SERVICE = "service"
    CERTIFICATE = "certificate"
    DNS_RECORD = "dns_record"
    COOKIE = "cookie"
    HEADER = "header"
    SCRIPT = "script"
    STORAGE = "storage"


class EdgeType:
    RESOLVES_TO = "resolves_to"
    HOSTED_ON = "hosted_on"
    USES_TECHNOLOGY = "uses_technology"
    RUNS_FRAMEWORK = "runs_framework"
    HAS_ENDPOINT = "has_endpoint"
    HAS_PARAMETER = "has_parameter"
    AUTHENTICATES_WITH = "authenticates_with"
    DEPLOYS_ON = "deploys_on"
    HAS_FINDING = "has_finding"
    SUPPORTS_EVIDENCE = "supports_evidence"
    LEADS_TO = "leads_to"
    DUPLICATE_OF = "duplicate_of"
    CORRELATED_WITH = "correlated_with"
    DISCOVERED_BY = "discovered_by"
    HAS_SUBDOMAIN = "has_subdomain"
    HAS_PORT = "has_port"
    RUNS_SERVICE = "runs_service"
    HAS_CERTIFICATE = "has_certificate"
    HAS_DNS_RECORD = "has_dns_record"
    HAS_SCRIPT = "has_script"
    HAS_STORAGE = "has_storage"
    USES = "uses"
    CONTAINS = "contains"
    REFERENCES = "references"
    MITIGATES = "mitigates"
    VERIFIES = "verifies"
